# Chirpy Configuration
remote_theme: cotes2020/jekyll-theme-chirpy

title: Nordic Economic Wiki
tagline: Økonomisk analyse av Norge og Sverige
description: En sammenlignende analyse av norsk og svensk økonomi (2024–2026).
url: "https://TorOEkle.github.io"
baseurl: "/llm-wiki"

# Site Settings
lang: nb-NO
timezone: Europe/Oslo

author:
  name: Tor Odin Ekle
  twitter: 
  github: TorOEkle

# Chirpy features
google_analytics:
  id: 
theme_mode: light # [light|dark]

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

# Layouts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author: Tor Odin Ekle

include:
  - raw
