title: Nordic Economic Wiki
description: A comparative analysis of the Norwegian and Swedish economies (2024-2026).
remote_theme: just-the-docs/just-the-docs

# Just the Docs Settings
color_scheme: light
search_enabled: true
nav_sort: Numbered

# Configuration for plugins
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - raw
